apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-resource-quota
  namespace: <namespace-name>
spec:
  hard:
    requests.cpu: "4"
    limits.cpu: "8"
    requests.memory: 8Gi
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    services.loadbalancers: "0"
    services.nodeports: "0"
    persistentvolumeclaims: "5"
    requests.storage: 100Gi
    configmaps: "20"
    secrets: "20"
